services:
  web-rise:
    image: web-rise:latest
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SPRING_R2DBC_URL=r2dbc:postgresql://postgres:5432/usersubscriptions
      - SPRING_R2DBC_USERNAME=postgres
      - SPRING_R2DBC_PASSWORD=daster
  postgres:
    image: postgres:17.5
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: daster
      POSTGRES_DB: usersubscriptions
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
volumes:
  postgres_data: