spring:
  api-docs:
    path: /api-docs
    swagger-ui:
      path: /swagger-ui.html
      operations-sorter: alpha
      tags-sorter: alpha
      display-request-duration: true
  r2dbc:
    url: r2dbc:postgresql://postgres:5432/usersubscriptions
    username: postgres
    password: daster
  data:
    r2dbc:
      repositories:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    com.example: INFO
server:
  port: 8080